spring:
  application:
    name: admin
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      #需要实时更新的目录
      additional-paths: static/**

zuul:
  sensitive-headers:
  routes:
    api:
      url: http://gateway.zhq.com:9070